### ISSUE TITLE
Error CURL

### ISSUE THREAD

**Issue by cdupasquier1980** [R11baka/deepai-php#1]
Hello,

Thank you for the client, I am very interested!

However, I have an error that I can't solve.  When I launch the client here is the PHP error

Warning: curl_error(): supplied resource is not a valid cURL handle resource in C:\wamp\www\colorize\vendor\r11baka\deepai\src\HttpClient\CurlClient.php on line 63

Thank you in advance for your help!

**Comment by R11baka** [comment]
Hello! Thank you for your issue. Can you provide additional information about error? How are you use client? Sorry for delayed answer, I have war in my country

**Comment by R11baka** [comment]
@cdupasquier1980 fixed error. Try to update package
